service: flask-netlify

provider:
  name: aws
  runtime: python3.8

functions:
  app:
    handler: wsgi.handler
    events:
      - http: 'GET /'
      - http: 'POST /upload'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: wsgi.app
    packRequirements: false
